### ISSUE TITLE
Sequence contains no elements

### ISSUE THREAD

**Issue by jekkkk** [LegoFigure11/Splat3GearView#5]
![image](https://user-images.githubusercontent.com/59463467/208219921-5bb16607-c663-4e50-b358-1005b2f26f2e.png)
Looks like it can't find something in the gear JSON files. Will post the full error log in the next comment

**Comment by jekkkk** [comment]
************** Exception Text **************
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Splat3GearView.Resources.GearData.FindGear(UInt16 ID, Byte Type) in C:\Users\Lego\Documents\GitHub\Splat3GearView\Splat3GearView\Resources\GearData.cs:line 55
   at Splat3GearView.Structures.Gear.SetInfoFromJSON() in C:\Users\Lego\Documents\GitHub\Splat3GearView\Splat3GearView\Structures\Gear.cs:line 50
   at Splat3GearView.MainWindow.Connect_ClickAsync(Object sender, EventArgs e) in C:\Users\Lego\Documents\GitHub\Splat3GearView\Splat3GearView\MainWindow.cs:line 94
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)

**Comment by jekkkk** [comment]
(Downloaded the nightly from the [other issue](https://github.com/LegoFigure11/Splat3GearView/issues/4))
